// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package prestore

import (
	"server/api/prestore"
)

type ControllerV1 struct{}

func NewV1() prestore.IPrestoreV1 {
	return &ControllerV1{}
}
