// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package workorder

import (
	"server/api/workorder"
)

type ControllerV1 struct{}

func NewV1() workorder.IWorkorderV1 {
	return &ControllerV1{}
}
