// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysCapitalDao is the data access object for the table sys_capital.
// You can define custom methods on it to extend its functionality as needed.
type sysCapitalDao struct {
	*internal.SysCapitalDao
}

var (
	// SysCapital is a globally accessible object for table sys_capital operations.
	SysCapital = sysCapitalDao{internal.NewSysCapitalDao()}
)

// Add your custom methods and functionality below.
