// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysUserBillDao is the data access object for the table sys_user_bill.
// You can define custom methods on it to extend its functionality as needed.
type sysUserBillDao struct {
	*internal.SysUserBillDao
}

var (
	// SysUserBill is a globally accessible object for table sys_user_bill operations.
	SysUserBill = sysUserBillDao{internal.NewSysUserBillDao()}
)

// Add your custom methods and functionality below.
