// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysAftersalesDao is the data access object for the table sys_aftersales.
// You can define custom methods on it to extend its functionality as needed.
type sysAftersalesDao struct {
	*internal.SysAftersalesDao
}

var (
	// SysAftersales is a globally accessible object for table sys_aftersales operations.
	SysAftersales = sysAftersalesDao{internal.NewSysAftersalesDao()}
)

// Add your custom methods and functionality below.
