// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysWitkeyChangeTitleDao is the data access object for the table sys_witkey_change_title.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyChangeTitleDao struct {
	*internal.SysWitkeyChangeTitleDao
}

var (
	// SysWitkeyChangeTitle is a globally accessible object for table sys_witkey_change_title operations.
	SysWitkeyChangeTitle = sysWitkeyChangeTitleDao{internal.NewSysWitkeyChangeTitleDao()}
)

// Add your custom methods and functionality below.
