// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysWorkOrderDao is the data access object for the table sys_work_order.
// You can define custom methods on it to extend its functionality as needed.
type sysWorkOrderDao struct {
	*internal.SysWorkOrderDao
}

var (
	// SysWorkOrder is a globally accessible object for table sys_work_order operations.
	SysWorkOrder = sysWorkOrderDao{internal.NewSysWorkOrderDao()}
)

// Add your custom methods and functionality below.
