// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysWitkeyLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysWitkeyLogDao = *internal.SysWitkeyLogDao

// sysWitkeyLogDao is the data access object for the table sys_witkey_log.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyLogDao struct {
	internalSysWitkeyLogDao
}

var (
	// SysWitkeyLog is a globally accessible object for table sys_witkey_log operations.
	SysWitkeyLog = sysWitkeyLogDao{
		internal.NewSysWitkeyLogDao(),
	}
)

// Add your custom methods and functionality below.
