// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysPrestoreDao is the data access object for the table sys_prestore.
// You can define custom methods on it to extend its functionality as needed.
type sysPrestoreDao struct {
	*internal.SysPrestoreDao
}

var (
	// SysPrestore is a globally accessible object for table sys_prestore operations.
	SysPrestore = sysPrestoreDao{internal.NewSysPrestoreDao()}
)

// Add your custom methods and functionality below.
