// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysSettlementDao is the data access object for the table sys_settlement.
// You can define custom methods on it to extend its functionality as needed.
type sysSettlementDao struct {
	*internal.SysSettlementDao
}

var (
	// SysSettlement is a globally accessible object for table sys_settlement operations.
	SysSettlement = sysSettlementDao{internal.NewSysSettlementDao()}
)

// Add your custom methods and functionality below.
