// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysWitkeyTitleDao is an internal type for wrapping the internal DAO implementation.
type internalSysWitkeyTitleDao = *internal.SysWitkeyTitleDao

// sysWitkeyTitleDao is the data access object for the table sys_witkey_title.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyTitleDao struct {
	internalSysWitkeyTitleDao
}

var (
	// SysWitkeyTitle is a globally accessible object for table sys_witkey_title operations.
	SysWitkeyTitle = sysWitkeyTitleDao{
		internal.NewSysWitkeyTitleDao(),
	}
)

// Add your custom methods and functionality below.
